refactor lock implement and fix mem usage bug
apache/hawq pull request #1499
Opened 2020-10-30 02:03 UTC by Librago

2020-10-30 02:08 UTC, huor commented on depends/dbcommon/src/dbcommon/log/logger.h
> +#define LOG_BACKSTRACE(...) COMPACT_LOG_BACKSTRACE(__VA_ARGS__)
LOG_BACKTRACE?

2020-10-30 02:13 UTC, huor requested changes
Change the name from "BACKSTRACE" to "BACKTRACE"

2020-10-30 02:53 UTC, huor approved these changes

2020-10-30 07:01 UTC, wcl14 approved these changes

2020-11-02 05:44 UTC, huor commented
The commit message should be in the format "HAWQ-xxxx. refactor lock implement and fix mem usage bug"

2020-11-12 03:37 UTC, huor approved these changes

2020-11-12 03:39 UTC, merged